"""initial migration

Revision ID: f5bbfa287fb5
Revises: 
Create Date: 2026-03-02 16:41:20.612238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bbfa287fb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('svnr', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('svnr', name=op.f('uq_user_svnr'))
    )
    op.create_table('mess',
    sa.Column('mess_id', sa.Integer(), nullable=False),
    sa.Column('date_mess', sa.DateTime(), nullable=False),
    sa.Column('wert', sa.Integer(), nullable=False),
    sa.Column('notiz', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_mess_user_id_user')),
    sa.PrimaryKeyConstraint('mess_id', name=op.f('pk_mess'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mess')
    op.drop_table('user')
    # ### end Alembic commands ###
